name: CI

on: [push]

jobs:
  #  build:
  #
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #    - uses: actions/checkout@v1
  #    - name: Run a one-line script
  #      run: echo Hello, world!
  #    - name: Run a multi-line script
  #      run: |
  #        echo Add other actions to build,
  #        echo test, and deploy your project.

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # 打包apk
      - name: Build with Gradle
        run: chmod +x gradlew &&./gradlew assembleRelease
      #      - name: "Run test suite"
      #         uses: msfjarvis/setup-android@1.0
      #         with:
      #          entrypoint: ./gradlew
      #          args: dependencies spotlessApply detekt assembleDebug
      #     上传apk 到action，在右上角查看
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk

        #获取apk版本号

        #向蒲公英上传文件

        #调用接口修改数据库的版本号


      #        向钉钉发送消息
      - name: Webhook
        uses: satak/webrequest-action@master
        with:
          url: https://oapi.dingtalk.com/robot/send?access_token=a2204bb5fa64dbb008881b5cf6be791d3bfa3a6e363c56364c11b237b62c3164
          method: POST
          payload: '{"msgtype": "text", "text": {"content": "github app 更新 内部版本号 ${{ env.VERSION_CODE }} 版本号 ${{ env.VERSION_NAME }}"}}'
          headers: 'Content-Type: application/json'