name: CI

on:
  push:
    branches:
      - master
    # 事件中要考虑的文件路径。 Optional; defaults to all.
    paths:
      - 'app/build.gradle'
jobs:
  #  build:
  #
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #    - uses: actions/checkout@v1
  #    - name: Run a one-line script
  #      run: echo Hello, world!
  #    - name: Run a multi-line script
  #      run: |
  #        echo Add other actions to build,
  #        echo test, and deploy your project.

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # 打包apk
      - name: Build with Gradle
        run: chmod +x gradlew &&./gradlew assembleRelease && echo $VERSION_NAME && echo "yml123123"

      #     上传apk 到action，在右上角查看
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk


      - name: echo
        run: echo "The pgyer_key was  ${{ secrets.pgyer_key }}"

        #向蒲公英上传文件
      - name: Upload To Pgyer
        uses: JantHsueh/webhook-action@master
        run:  curl -F 'file=@app/build/outputs/apk/release/app-release.apk' -F '_api_key=${{ secrets.pgyer_key }}' -F 'buildInstallType=3' https://www.pgyer.com/apiv2/app/upload

        #获取apk版本号
      - name: GetApiInfo
        id: apk
        uses: JantHsueh/get-apk-version-action@master

      # 调用接口修改数据库的版本号
      - name: Update SoftwareVersion
        uses: satak/webrequest-action@master
        with:
          url: https://www.adsff123.com/app/guest/updateSoftwareVersion
          method: POST
          payload: '{"id":1,"softwareType":1,"version":"${{ steps.apk.outputs.versionNum }}","versionDesc":"app更新时间 ${{ steps.apk.outputs.time}}","versionNum":${{ steps.apk.outputs.versionCode }}}'
          headers: '{"Content-Type": "application/json","authorization":"Cs_SfVScr2019","platform":"android"}'

      #        向钉钉发送消息
      - name: dingtalk
        uses: satak/webrequest-action@master
        with:
          url: https://oapi.dingtalk.com/robot/send?access_token=a2204bb5fa64dbb008881b5cf6be791d3bfa3a6e363c56364c11b237b62c3164
          method: POST
          payload: '{"msgtype": "text", "text": {"content": "github App更新 内部版本号${{ steps.apk.outputs.versionCode }} 版本号 ${{ steps.apk.outputs.versionNum }}"}}'
          headers: '{"Content-Type": "application/json"}'