name: CI

on:
  push:
    branches:
      - master
    # 事件中要考虑的文件路径。 Optional; defaults to all.
#    paths:
#      - 'app/build.gradle'
jobs:

  first-job:
    runs-on: ubuntu-latest
    steps:
      step1:
        #获取指定时区的时间
        - name: Get Time
          id: time
          uses: JantHsueh/get-time-action@master
          with:
            timeZone: 6


        #获取指定时区的时间
        - name: Get Time
          id: time1
          uses: JantHsueh/get-time-action@master
          with:
            timeZone: 7
      step2:
        #获取指定时区的时间
        - name: Get Time
          id: time
          uses: JantHsueh/get-time-action@master
          with:
            timeZone: 6


        #获取指定时区的时间
        - name: Get Time
          id: time1
          uses: JantHsueh/get-time-action@master
          with:
            timeZone: 7

  second-job:
    runs-on: ubuntu-latest
    steps:
      #获取指定时区的时间
      - name: Get Time
        id: time2
        uses: JantHsueh/get-time-action@master
        with:
          timeZone: 8
